// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA804593O8JK9MbnnlbR3PDPA32o8rIkfk',
    appId: '1:564361281665:web:f4aca5a8520d42e106cd80',
    messagingSenderId: '564361281665',
    projectId: 'fashion-app-1bd94',
    authDomain: 'fashion-app-1bd94.firebaseapp.com',
    storageBucket: 'fashion-app-1bd94.firebasestorage.app',
    measurementId: 'G-QJCZQ80CRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0k-a0LA-sqAidYeMzH0NfAe81n5GAoQ',
    appId: '1:57590800132:android:00ccdc8a7d623265657a51',
    messagingSenderId: '57590800132',
    projectId: 'mifra-fashin-stores',
    databaseURL: 'https://mifra-fashin-stores-default-rtdb.firebaseio.com',
    storageBucket: 'mifra-fashin-stores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk0trpTjAxIPsE_Ghqr7ICWiU0UWXkmhs',
    appId: '1:564361281665:ios:8a11fde045e2e58306cd80',
    messagingSenderId: '564361281665',
    projectId: 'fashion-app-1bd94',
    storageBucket: 'fashion-app-1bd94.firebasestorage.app',
    iosBundleId: 'com.mifra.mifraFashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk0trpTjAxIPsE_Ghqr7ICWiU0UWXkmhs',
    appId: '1:564361281665:ios:8a11fde045e2e58306cd80',
    messagingSenderId: '564361281665',
    projectId: 'fashion-app-1bd94',
    storageBucket: 'fashion-app-1bd94.firebasestorage.app',
    iosBundleId: 'com.mifra.mifraFashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA804593O8JK9MbnnlbR3PDPA32o8rIkfk',
    appId: '1:564361281665:web:1744e66c82499cf006cd80',
    messagingSenderId: '564361281665',
    projectId: 'fashion-app-1bd94',
    authDomain: 'fashion-app-1bd94.firebaseapp.com',
    storageBucket: 'fashion-app-1bd94.firebasestorage.app',
    measurementId: 'G-NHKYHB5MRX',
  );
}